# Generated by Django 6.0.1 on 2026-02-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
    ]
