# Generated by Django 6.0.1 on 2026-02-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=12, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
