# Generated by Django 6.0.1 on 2026-03-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
